version: "3.7"

services:
  client:
    build: ./client
    environment:
    ports:
      - "3000:3000"
    command:
  server:
    build: ./server
    environment:
    ports:
      - "4000:4000"
    command:

networks:
  hackernews:
