version: "2.4"

services:
  hn_database:
    container_name: hn_database
    ports:
      - "5444:5432"
    image: postgres:13.3-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

  hn_dashboard:
    container_name: hn_dashboard
    image: adminer
    restart: always
    depends_on:
      - hn_database
    ports:
      - 8881:8080

volumes:
  postgres:
