version: "3.7"

services:
  server:
    build: ./server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      labels:
        - traefik.frontend.rule=Host:hackernews.asjas.co.za
        - traefik.enable=true
        - traefik.protocol=https
        - traefik.backend=traefik
        - traefik.port=4000
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - web

networks:
  web:
