debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    permanent = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
  [entryPoints.dashboard]
  address = ":8080"
  compress = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
domain = "hackernews.asjas.co.za"
swarmMode = true
swarmModeRefreshSeconds = "30s"
network = "hackernews_web"
exposedByDefault = false

[api]
dashboard = true
entryPoint = "dashboard"

[acme]
email = "admin@asjas.co.za"
storage = "/letsencrypt/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
onHostRule = true
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "hackernews.asjas.co.za"
